name: Hexo Deploy

on:
  push:
    branches:
      - main # 只有当 main 分支有变动时才触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate and Deploy
        env:
          GH_TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          # 1. 配置身份信息
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 2. 【核心重头戏】全局重定向：
          # 这一行命令会让所有 github.com 的 https 链接自动带上 Token
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          
          # 3. 执行部署
          npx hexo clean
          npx hexo generate
          npx hexo deploy